apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-logs
spec:
  accessModes:
    {{- toYaml .Values.persistence.logs.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}