image:
  repository: php
  tag: "8.2-apache"

persistence:
  logs:
    storageClass: standard
    size: 1Gi

promtail:
  enabled: true
  lokiPushUrl: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push

secretData:
  username: <path:secret/data/argocd/test#username>
  password: <path:secret/data/argocd/test#password>

mysql:
  enabled: true
  auth:
    database: <path:secret/data/argocd/app-a#MYSQL_DATABASE>
    username: <path:secret/data/argocd/app-a#MYSQL_USERNAME>
    password: <path:secret/data/argocd/app-a#MYSQL_PASSWORD>
    rootPassword: <path:secret/data/argocd/app-a#MYSQL_ROOT_PASSWORD>