image:
  repository: php
  tag: "8.2-apache"

persistence:
  logs:
    storageClass: standard
    size: 1Gi

mysql:
  host: mysql.app-a.svc.cluster.local
  port: 3306
  database: laravel
  username: laravel
  password: laravelpass

promtail:
  enabled: true
  lokiPushUrl: http://loki-gateway.logging.svc.cluster.local/loki/api/v1/push