image:
  repository: php
  tag: "8.2-apache"

persistence:
  logs:
    storageClass: standard
    size: 1Gi

mysql:
  host: mysql.app-c.svc.cluster.local
  port: 3306
  database: laravel
  username: laravel
  password: laravelpass

promtail:
  enabled: false

secretData:
  username: <path:secret/data/argocd/test#username>
  password: <path:secret/data/argocd/test#password>  